server:
  port: 8089

mybatis:
  type-aliases-package: com.java.toworkservice.entity
#sql打印
logging:
  level:
    com:
      example:
        qhit:
          exam:
            mapper: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    ip-address: 127.0.0.1
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/em?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
  application:
    name: towork-server